import os
import re
import logging
from pathlib import Path
from anthropic import Anthropic

from src.ai_engine.prompts import CODE_GEN_SYSTEM_PROMPT, build_code_gen_prompt
from src.ai_engine.exceptions import TestGenerationError

logger = logging.getLogger(__name__)


class CodeWriter:
    """
    แปลง test case (dict) เป็นโค้ด Playwright + pytest
    แล้ว save เป็นไฟล์ .py ในโฟลเดอร์ tests/generated/
    """

    def __init__(self, api_key: str | None = None, output_dir: str = "tests/generated"):
        self.client = Anthropic(api_key=api_key or os.getenv("ANTHROPIC_API_KEY"))
        self.model = "claude-sonnet-4-6"
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(parents=True, exist_ok=True)

    def generate_code(self, test_case: dict, page_context: str) -> str:
        """เรียก Claude เพื่อแปลง test case เป็นโค้ด Playwright (คืนค่าเป็น string)"""
        response = self.client.messages.create(
            model=self.model,
            max_tokens=2048,
            temperature=0.2,
            system=CODE_GEN_SYSTEM_PROMPT,
            messages=[
                {"role": "user", "content": build_code_gen_prompt(test_case, page_context)}
            ]
        )
        code = response.content[0].text
        return self._clean_code(code)

    def _clean_code(self, code: str) -> str:
        """ลบ markdown code block ออก เผื่อ Claude ใส่มาทั้งที่เราห้ามแล้ว"""
        code = re.sub(r"^```python\s*\n", "", code)
        code = re.sub(r"^```\s*\n", "", code)
        code = re.sub(r"\n```\s*$", "", code)
        return code.strip()

    def write_to_file(self, test_case: dict, page_context: str) -> Path:
        """generate โค้ดและ save เป็นไฟล์ คืนค่า path ของไฟล์ที่สร้าง"""
        code = self.generate_code(test_case, page_context)

        safe_id = test_case["id"].lower().replace("-", "_")
        filename = f"test_{safe_id}.py"
        filepath = self.output_dir / filename

        header = (
            f"# Auto-generated by AI Test Case Generator\n"
            f"# Test Case ID: {test_case['id']}\n"
            f"# Title: {test_case['title']}\n\n"
        )

        try:
            filepath.write_text(header + code, encoding="utf-8")
            logger.info("Generated test file: %s", filepath)
            return filepath
        except OSError as e:
            raise TestGenerationError(f"ไม่สามารถเขียนไฟล์ {filepath}: {e}") from e